### ISSUE TITLE
Pre-Push Commit Limit Documentation Mismatch

### ISSUE THREAD

**Issue by rgajason** [GitGuardian/ggshield#105]
According to the documentation on PyPI, GGShield pre-push hooks will scan up to 100 commits:

https://pypi.org/project/ggshield/

> Pre-push hooks will not scan more than a 100 commits to avoid developer interruption. In case there are more than a 100 commits in a push the hook will be skipped.

In practice there appears to be a 50 commit limit:

```
% ggshield --version
ggshield, version 1.8.1
% git push -u origin feature/my-new-big-branch
New tree event. Scanning last 50 commits.
Too many commits. Scanning last 50 commits

Scanning Commits  [####################################]  100% 
...
```

**Comment by Jguer** [comment]
Hi @rgajason , you're correct that the public documentation has fallen out of sync on this issue. 

There is a new config option called `max_commits_for_hook` that defaults to 50 and can be configured through the `.gitguardian.yaml`

The documentation will be updated to reflect this
