### ISSUE TITLE
Input: Pypi packages

### ISSUE THREAD

**Issue by ericfourrier** [GitGuardian/ggshield#113]
**Is your feature request related to a problem? Please describe.**

I want to scan packages (before publishing them to a registry but also be able to download from a registry and scan the package for secrets) 

**Describe alternatives you've considered**

Maybe scanning a tar.gz since a package is a path. Maybe path should support compressed directory and ggshield should handle the decompression.

## Commands

- `ggshield scan pypi <package-name>`

Given a package-name, ggshield will attempt to pull from pip the wheel and then scan the full archive

- `ggshield scan archive <archive_path>`

Given an archive path, ggshield will attempt to download the archive if an url and then scan the full archive.

**Comment by agateau-gg** [comment]
This has been implemented in https://github.com/GitGuardian/ggshield/pull/176.
