### ISSUE TITLE
Print a message when no secrets are detected

### ISSUE THREAD

**Issue by jeremyds** [GitGuardian/ggshield#117]
**Is your feature request related to a problem? Please describe.**
when ggshield does not detect secret and the verbose mode is not set, there is no output and the cli only returns a zero no error code. Although it is compliant with linux tool philosophy, it is not always clear for our users / customers that the scanning was successful and that there are no leaks. 

**Describe the solution you'd like**
This issue goal is more to track the output issue and think about it. To tackle the lack of information described above, we can either always output a clear message like "No leak found" even if the verbose mode is not set, or we can make the verbose mode set by default.

**Comment by rgajason** [comment]
👍 yes, please

My vote is that even non-verbose usage reports a simple "all clear" message.  As we've rolled this out to developers a frequent question is "how do I know it is working?" because pre-commit checks are silent when no issues found.
