### ISSUE TITLE
Add to nixpkgs

### ISSUE THREAD

**Issue by ari-becker** [GitGuardian/ggshield#138]
Please add `ggshield` to `nixpkgs`: https://github.com/NixOS/nixpkgs#contributing

This will allow people using the Nix package manager to install `ggshield`, including the ability to automatically download `ggshield` when they clone a repository that uses it ( https://nixos.wiki/wiki/Development_environment_with_nix-shell ).

**Comment by jeremyds** [comment]
Hello @ari-becker,
Thanks for your input, we really appreciated it! Unfortunately we don't have short term plan to add ggshield to nixpkgs. We aim to use [fpm](https://github.com/jordansissel/fpm) to build packages for that purpose. The first step would be to build packages only.
