### ISSUE TITLE
Factorize export handler code

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#140]
## The problem

There is some duplicated code between the [text](https://github.com/GitGuardian/ggshield/blob/2097e18b9c9b3c14efa73a089b97e01412ea4873/ggshield/output/text/text_output.py) and [json](https://github.com/GitGuardian/ggshield/blob/2097e18b9c9b3c14efa73a089b97e01412ea4873/ggshield/output/json/json_output.py) output handler implementations.

By refactoring the existing handlers to reduce the amount of duplicated code before implementing new output handlers we can avoid spreading the problem.

### Line creation

The code creating lines from content and taking into account the `--show-secrets` option can be factorized. Move it to a helper function in `OutputHandler`, or as a standalone function if it does not need the handler instance.

### Factorize final output handling

The code to write to either the destination file or to stdout is duplicated. This can be fixed by splitting `OutputHandler.process_scan()` in two: move the common code to the currently empty `OutputHandler.process_scan()` and make `OutputHandler.process_scan()` call a `_process_scan_impl()` method, implemented by the concrete output handler implementation.

This would look roughly like this:

```py
class OutputHandler:
    def process_scan(self, scan: ScanCollection) -> int:
        """
        Returns:
            exit code
        """
        content, return_code = self._process_scan_impl(scan)
        # handle output
        return return_code
        
    def _process_scan_impl(self, scan: ScanCollection, top: bool=True) -> Tuple[str, int]
        """
        Returns:
            tuple of (handler text, exit code)
        """
        pass
```

This has the additional benefit of hiding the `top` argument, which is an implemention detail.

### Remove `OutputHandler.process_result()`

This method should not be part of `OutputHandler` API: it's only called by `OutputHandler` implementations, not by `OutputHandler` itself or `OutputHandler` users. Implementation classes are free to create one, but it's not a requirement.

This is not a real factorization, but it makes the API cleaner.

**Comment by jeremyds** [comment]
Looks good to me.

Maybe a minor other thing to do:

`leak_message_located` function is 100 lines long and has 7 levels of indentation, making hard to read / understand. I would advocate to split it and maybe apply the usual pattern to reduce indentation:
```
for xxx:
    if yyy:
        do something
        if zzz:
             do another thing
```
=>
```
for xxx:
    if not yyy:
         continue
    do something
    if not zzz:
         continue
    do another thing
```

**Comment by agateau-gg** [comment]
Indeed, it could use some split and/or early returns! But that code is not duplicated in the json handler so I think that can be a separate issue.
