### ISSUE TITLE
ggshield scan docker misses some files

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#193]
**GitGuardian Shield Version**

- 1.11.0

**Describe the bug**

1. Unpack this archive: [missed-secret.zip](https://github.com/GitGuardian/ggshield/files/8415919/missed-secret.zip)
2. Create a Docker image from it:
```
cd missed-secret
docker build -t missed-secret:1 .
```
3. Scan the image:
```
ggshield scan docker missed-secret:1
```

→ No secrets are found.

4. Change the `COPY` line in the Dockerfile to:
```
COPY index.py /index.py
```

5. Rebuild the Docker image:
```
docker build -t missed-secret:2 .
```
6. Scan the image:

```
ggshield scan docker missed-secret:2
```

→ Secret is found.

**Comment by pierrelalanne** [comment]
This seems linked to this banlist : https://github.com/GitGuardian/ggshield/blob/main/ggshield/scan/docker.py#L14
