### ISSUE TITLE
Detect hardhat and wallet private keys

### ISSUE THREAD

**Issue by danicuki** [GitGuardian/ggshield#254]
**Is your feature request related to a problem? Please describe.**
I am trying to configure my repo to use pre-commit key detections:

https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit

But it is not working with hardhat.config.js private keys:
```
module.exports = {
  defaultNetwork: 'polygon',
  solidity: '0.8.4',
  networks: {
    hardhat: {},

    rinkeby: {
      url: 'https://eth-rinkeby.alchemyapi.io/v2/MY_KEY',
      accounts: [
        '0xMY_OTHER_KEY',
      ],
    },
}
```

**Describe the solution you'd like**
Support hardhat config keys

**Describe alternatives you've considered**
no alternatives

**Additional context**
no additional context

**Comment by agateau-gg** [comment]
Unfortunately, we currently do not support Alchemy secrets. It's in our backlog but is not considered high priority for now.

**Comment by pierrelalanne** [comment]
Hello @danicuki,
This was added to our secrets detection engine. The changes should hit production in two weeks.
Thank you for your feedback !
