### ISSUE TITLE
`ggshield secret scan repo` spams the terminal

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#265]
**GitGuardian Shield Version**

- v1.12.0

**Describe the bug**

When scanning a repository using `ggshield secret scan repo`, ggshield prints "No secrets have been found" for each scanned commit.

**Expected behavior**

ggshield should print "No secrets have been found" only once, at the end.

**Comment by deimosfr** [comment]
Getting the same issue
