### ISSUE TITLE
Do not abort repo scan if a commit fails to scan

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#267]
## The problem

When `ggshield secret scan repo` fails to scan a commit, it stops. This is annoying because it forces users to restart the full scan.

## Proposed solution

The command should note all failures and carry on. At the end it should summarize all failures and exit with an error.

To be decided: in the case of JSON output, should the failure summary be part of the JSON document or should it be sent directly to stderr?

**Comment by pierrelalanne** [comment]
@agateau-gg : I think we should prioritize this and work on it in the next sprint. Do you agree ?

**Comment by agateau-gg** [comment]
> @agateau-gg : I think we should prioritize this and work on it in the next sprint. Do you agree ?

Sounds good :+1:

**Comment by agateau-gg** [comment]
Thanks for your feedback @dghowlett.

Note however that the failures this issue is talking about are bugs in ggshield preventing it from scanning a commit. They are not incidents: incidents are already included in the JSON output.

This means the failure is likely to be of little interest to users, except for opening an issue or working around a bug. In normal usage, ggshield should *not* fail to scan a commit.

There is the case of the network issue though, that would cause a failure to scan which would not be a ggshield bug 🤔.
