### ISSUE TITLE
Only warn on unknown configuration keys, do not fail

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#278]
## Description

Given a configuration file with an unknown configuration key:

```
$ cat > .gitguardian.yaml <<EOF
heredoc> version: 2
heredoc> unknown: bla
heredoc> EOF
```

ggshield from the iac branch currently fails:

```
$ ggshield api-status                                                     
Error: Error in ./.gitguardian.yaml:
unknown: ['Unknown field.']
```

Compare with the behavior of ggshield from the main branch:

```
$ ggshield api-status
Unrecognized key in config: version
Unrecognized key in config: unknown
API URL: https://api.gitguardian.com
Status: healthy
App version: v2.8.0
Secrets engine version: 2.70.0
```

We need to bring back this behavior: it is critical that users of ggshield vX.Y can continue to run ggshield even if the configuration file contains keys used by ggshield vX.Y+1.

**Comment by GG-HH** [comment]
Closed by #286
