### ISSUE TITLE
ggshield auth login --method=token Error

### ISSUE THREAD

**Issue by nourafyz** [GitGuardian/ggshield#281]
**GitGuardian Shield Version**

- [ ] I can reproduce this bug in the latest version

**Command executed**

`ggshield secret scan ...`

**Describe the bug**

**Expected behavior**

**Screenshots**

**Traceback (if available)**

**Comment by nourafyz** [comment]
I'm trying to authenticate using a token. I want to pass the token in the command line, similar to the following example:
![Screen Shot 2022-06-30 at 4 54 35 PM](https://user-images.githubusercontent.com/90372812/176797001-3b97720f-7258-4cc0-aa1b-a267f22be651.png)
source: https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/auth/login 

However, I get the following error:
Error: Got unexpected extra argument (xxxxxx)

**Comment by agateau-gg** [comment]
> I'm trying to authenticate using a token. I want to pass the token in the command line, similar to the following example: ![Screen Shot 2022-06-30 at 4 54 35 PM](https://user-images.githubusercontent.com/90372812/176797001-3b97720f-7258-4cc0-aa1b-a267f22be651.png) source: https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/auth/login
> 
> However, I get the following error: Error: Got unexpected extra argument (xxxxxx)

Oh, the documentation is wrong. I am going to get it fixed.

We do not support passing the token on the command-line. This is to avoid having your token stored in clear-text in your shell history file. The working syntax is `ggshield auth login --method=token` without any arguments. ggshield will then prompt you to enter the token.

**Comment by agateau-gg** [comment]
Documentation has been updated.
