### ISSUE TITLE
Getting 403:Quota limit reached error while scanning the repo

### ISSUE THREAD

**Issue by venkatn087** [GitGuardian/ggshield#296]
Hi Team,

we are much interested on your product and while scan the repo to give to the Demo to the  internal team we are getting an error message as mentioned below.

brsubbareddy123@gitgaurdian WebGoat]$ ggshield --version
ggshield, version 1.12.0
[brsubbareddy123@gitgaurdian WebGoat]$ git --version
git version 1.8.3.1
[brsubbareddy123@gitgaurdian WebGoat]$ 

Repo name what we have scanned  is :  https://github.com/WebGoat/WebGoat.git
i have clone the the repo into git directory.

[brsubbareddy123@gitgaurdian ~]$ mkdir gitrepocode
[brsubbareddy123@gitgaurdian ~]$ cd gitrepocode/
[brsubbareddy123@gitgaurdian gitrepocode]$ git init
Initialized empty Git repository in /home/brsubbareddy123/gitrepocode/.git/
[brsubbareddy123@gitgaurdian gitrepocode]$ git clone https://github.com/WebGoat/WebGoat.git
Cloning into 'WebGoat'...
remote: Enumerating objects: 42408, done.
remote: Total 42408 (delta 0), reused 0 (delta 0), pack-reused 42408
Receiving objects: 100% (42408/42408), 99.31 MiB | 31.03 MiB/s, done.
Resolving deltas: 100% (19658/19658), done.
[brsubbareddy123@gitgaurdian gitrepocode]$ ls -ltr
total 4
drwxrwxr-x. 8 brsubbareddy123 brsubbareddy123 4096 Jul 13 06:05 WebGoat
[brsubbareddy123@gitgaurdian gitrepocode]$ cd
[brsubbareddy123@gitgaurdian ~]$ ggshield secret scan repo gitrepocode/WebGoat/
Scanning Commits  [###---------------------------------]    9%  00:03:03
Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [###---------------------------------]    9%  00:03:06
Error scanning. Results may be incomplete.
Add the following file to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [###---------------------------------]    9%  00:03:05
Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]

Error scanning. Results may be incomplete.
Add the following file to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [#####-------------------------------]   15%  00:03:16
Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]

Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [######------------------------------]   16%  00:03:40
Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]

Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]

Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]

Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [######------------------------------]   18%  00:04:16
Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]

Error scanning. Results may be incomplete.
Add the following files to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [######------------------------------]   19%  00:04:16
Error scanning. Results may be incomplete.
Add the following file to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [######------------------------------]   19%  00:04:15
Error scanning. Results may be incomplete.
Add the following file to your paths-ignore:
- : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]
Scanning Commits  [######------------------------------]   19%  00:04:14
Error scanning. Results may be incomplete.
The following chunk is affected:
src/main/webapp/webgoat.jsp
403:Quota limit reached.
Scanning Commits  [#######-----------------------------]   19%  00:04:14
Error scanning. Results may be incomplete.
The following chunk is affected:
src/main/java/org/owasp/webgoat/lessons/Challenge2Screen.java
403:Quota limit reached.

Error scanning. Results may be incomplete.
The following chunk is affected:
webgoat/src/main/java/org/owasp/webgoat/lessons/Challenge2Screen.java
403:Quota limit reached.
Scanning Commits  [#######-----------------------------]   19%  00:04:15
Error scanning. Results may be incomplete.
The following chunk is affected:
src/main/java/org/owasp/webgoat/lessons/PasswordStrength.java
403:Quota limit reached.

Error scanning. Results may be incomplete.
The following chunk is affected:
webgoat/src/main/java/org/owasp/webgoat/lessons/PasswordStrength.java
403:Quota limit reached.

could you please let me know why are we getting 403: Quota limit reached error here
and also 
why as i getting error - : filename:: [ErrorDetail(string='This field may not be blank.', code='blank')]   

thanks 
venkat

**Comment by agateau-gg** [comment]
Hi Venkat,

I investigated your filename bug and found out the issue is caused by filename with spaces. We have a bug to fix here, I expect the fix will be the same as the one for #273. This fix is scheduled for the next release, 1.13.0.

Regarding your quota issue: ggshield uses a system of quota on API calls to avoid overloading our servers. The problem is: scanning all commits of a repository with ggshield can consume them quickly. If you need more quota to help you evaluate the product, feel free to get in touch with our support team on support@gitguardian.com.

**Comment by agateau-gg** [comment]
I am closing this now because the issue regarding filenames with spaces has been fixed.
