### ISSUE TITLE
Look for updates and alert the user when available

### ISSUE THREAD

**Issue by Walz** [GitGuardian/ggshield#299]
**Is your feature request related to a problem? Please describe.**
Users are not informed when a new version is released, unless they watch the repository on GitHub.

**Describe the solution you'd like**
An optional feature to look for the version number of the latest version and print a warning when a newest version is available when ggshield is executed.

**Describe alternatives you've considered**
A new command to look for update, it would be less intrusive but only alert users who go out of their way to use it.

**Comment by eletronicacentauro** [comment]
don't get on my page the answers to the questions, i apena the message of hello world
(Wit Ai Messenger Bot Exemple- Glitc)
