### ISSUE TITLE
How to configure ggshield/giugaurding with GitKraken/Intellij Editors 

### ISSUE THREAD

**Issue by venkatn087** [GitGuardian/ggshield#316]
Hi Team,

Could you please let me know how to integrate gitgaurdian/ggshield tool with intellij/VS code editor?
And also can we integrate GitGaurdian/ggshield with GitKraken?

Thanks
Venkat

**Comment by agateau-gg** [comment]
Hi,

It is currently not possible to integrate ggshield with IDEs.

As for GitKraken, I would expect installing ggshield as a pre-commit hook would be good enough. Do you have something else in mind?
