### ISSUE TITLE
Bumb python-dotenv dependency to 0.20 (the new minor)

### ISSUE THREAD

**Issue by furioness** [GitGuardian/ggshield#332]
**GitGuardian Shield Version**

- [1.13.0 ] I can reproduce this bug in the latest version

**Describe the bug**

Please, bump python-dotenv dependency to 0.20 (the latest minor).
I had got a dependency error, so had to downgrade on my side. 
I guess you would agree that this isn't a good solution -  having the latest stuff on your side is more correct.
Thank you.

**Traceback (if available)**
>poetry add --dev ggshield

>Because no versions of ggshield match >1.13.0,<2.0.0 and ggshield (1.13.0) depends on python-dotenv (>=0.19.1,<0.20.0), ggshield (>=1.13.0,<2.0.0) requires python-dotenv (>=0.19.1,<0.20.0).
  So, because datagen depends on both python-dotenv (^0.20.0) and ggshield (^1.13.0), version solving failed.

**Comment by agateau-gg** [comment]
Good point, will look into it. In the mean time, since ggshield is not a Python library, you can install it using [pipx](https://pypa.github.io/pipx/) to avoid dependency issues.
