### ISSUE TITLE
Doc for ggshield config unset is a copy of the one for ggshield config set

### ISSUE THREAD

**Issue by Kariss83** [GitGuardian/ggshield#367]
## Environment

- ggshield version: 1.13.3

## Describe the bug

When you go to [the online documentation for ggshield config unset](https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/config/unset) you end up on a copy of the page for ggshield set and no documentation is available for the unset command.

Steps to reproduce:

1. Go to : https://docs.gitguardian.com/internal-repositories-monitoring/ggshield/reference/config/unset

Actual result:

![image](https://user-images.githubusercontent.com/43004632/193063617-90728d73-878a-4d8e-bc24-e58748ad2567.png)

Expected result:

![image](https://user-images.githubusercontent.com/43004632/193064518-f0379812-ba19-44f0-adea-4144c65f8253.png)

**Comment by agateau-gg** [comment]
Took a bit longer than expected, but it's now fixed.
