### ISSUE TITLE
ggshield fails with long paths

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#391]
## Environment

- ggshield version: 1.13.5
- Operating system (Linux, macOS, Windows): any
- Operating system version: any
- Python version: 3.8.10

## Describe the bug

When scanning a file whose path is longer than 255, ggshield fails.

Steps to reproduce:

1. Create a long file. Can be done with:
   ```
   mkdir tmp  # use a dir because Python does not want to create a file longer than 255 chars
   python -c 'open("tmp/" + "l" * 255, "w").write("foo")'
   ```
3. Run command `ggshield secret scan path tmp/l*`

Actual result:

```
Scanning Path... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1 files scanned out of 1 0:00:00
Error: Error scanning, network error occurred: {0: {'filename': ['Longer than maximum length 256.']}}
```

Expected result: Scan should succeed

**Comment by cyprianbergoniatmo** [comment]
Can we re-open this issue, we are still seeing it on 1.13.6
