### ISSUE TITLE
git guardian github action bug

### ISSUE THREAD

**Issue by karkir0003** [GitGuardian/ggshield#447]
## Environment

- ggshield version: latest
- Operating system (Linux, macOS, Windows): windows
- Python version: 3.9

## Describe the bug

Getting this error when I run git guardian in github action workflow

Permission denied: '/github/home/.cache'

Steps to reproduce:

1. copy this github action code at https://dashboard.gitguardian.com/workspace/335609/settings/workspace/integrations/github_actions into github action workflow yml file
2. Commit/push to dev branch
3. observe github action

Actual result:

Permission denied: '/github/home/.cache'

Expected result:

result showing scan and pass/fail for any vulnerability

If applicable, add logs or screenshots to help explain your problem.

**Comment by karkir0003** [comment]
@CharlesB2 @agateau-gg

**Comment by pierrelalanne** [comment]
Hello @karkir0003,
Thank you for reporting this behavior. In order for us to move forward, could you provide us with :
- A link to the failing action run ? (If your repo is public)
- Alternatively, an extract from the logs of the GitHub action ?
- Do you know which ggshield Docker image was used ? Would you have a tag in the logs ?

**Comment by pierrelalanne** [comment]
Thanks for your answer. 
From what I can see, the action runs correctly.

The message you see is a log message that warns about insufficient rights to cache the latest version of ggshield available. This is used to warn the user if they use an old version of ggshield, but it does not affect the run.  

Note that following #450 : we re-introduce the success message when no secrets are found. This should make the output more explicit.

**Comment by pierrelalanne** [comment]
I am closing this issue as we improved the logs and re-introduced an explicit success message.  
Thanks for your feedbacks.
