### ISSUE TITLE
All Clear Message Missing in 1.14

### ISSUE THREAD

**Issue by rgajason** [GitGuardian/ggshield#448]
## Environment

- ggshield version: 1.14.2
- Operating system (Linux, macOS, Windows): macOS
- Operating system version: 12.6
- Python version: 3.10.8

## Describe the bug

1. Configure GGShield as pre-commit hook
2. Execute a `git commit` that does not include a secret

Actual result:

No output from GGShield indicating a clean scan

Expected result:

In previous versions the following message would be displayed:

> No secrets have been found

**Comment by pierrelalanne** [comment]
Hello @rgajason,  
Thanks for reporting this issue.  
We indeed recently changed the content of ggshield's output. I understand that this new behavior can be less clear.  
We will look into improving this shortly. I will keep you updated on this ticket.
