### ISSUE TITLE
ggshield is not picking up Hashicorp Vault access token on scan

### ISSUE THREAD

**Issue by tushar5526** [GitGuardian/ggshield#459]
## Environment

- ggshield version: ggshield, version 1.14.2
- Operating system (Linux, macOS, Windows): Ubuntu
- Operating system version: 22.04
- Python version: 3.8.10

## Describe the bug

Hashicorp vault access tokens are not being flagged as a secret when scanned using ggshield.

Steps to reproduce:

1. Install ggshield
2. Write the Hashicorp vault token to a file
3. scan the file

Actual result:

Passes without fail.
Expected result:

Should flag that a token exists and pre-commit hook should fail. 

If applicable, add logs or screenshots to help explain your problem.

**Comment by pierrelalanne** [comment]
Hello @tushar5526,
Thank you for your feedback. 
Would you have a code snippet (redacted if needed) to illustrate the case you are describing ?

**Comment by tushar5526** [comment]
I am using secrets in my ansible playbook to fetch data from [Hashicorp Vault](https://www.vaultproject.io/). To access the vault you generate an access token. `ggshield` is not able to identify the vault root token. 

The root token is generated when you start the vault. [Installing and starting vault](https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-dev-server)

![image](https://user-images.githubusercontent.com/30565750/214381581-7119f21e-90a5-4c2b-a3d7-929e3d35d241.png)

**Comment by tushar5526** [comment]
I am interested to take a look at this bug if it is available to fix and currently not picked up by anyone.

**Comment by pierrelalanne** [comment]
Hello @tushar5526,
I'm sorry but our detection engine is not open source, we will be fixing this on the server side.
If you still want to contribute to the client, you can pick an issue with label `good_first_issue`. For instance #413 🙂 
Thank you for your interest in GitGuardian.

**Comment by pierrelalanne** [comment]
This issue has been fixed in the latest release of our detection engine, the one currently used by ggshield.  
I am closing this issue. Thanks for reporting the bug.
