### ISSUE TITLE
Represent files as Path instead of str

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#464]
Many GGShield functions work with files from the local filesystem. These functions could benefit from using Python pathlib to represent files as Path instead of str. The benefits would be the following:

- make the code more self-explanatory: a `Path` argument type is more precise than an `str`
- simplify code: reading and writing files is simpler with Path
- potentially catch bugs

**Comment by DataDavD** [comment]
👋 hey @agateau-gg is that cool if I give this a go, please?

**Comment by agateau-gg** [comment]
> wave hey @agateau-gg is that cool if I give this a go, please?

Sure, go for it! 👍🏻

**Comment by DataDavD** [comment]
hey @agateau-gg I just want to make sure I'm on the right page before refactoring. Is this a good example of what you were referring to that should be change to the `Path` type from `str`? https://github.com/DataDavD/ggshield/blob/3a04c006698db80bdb0ff26dc63105e7dcb7e785/ggshield/core/config/utils.py#L26

Thanks in advance for verifying!

**Comment by agateau-gg** [comment]
Yes, that's a good example :+1:

**Comment by RaoufCherif** [comment]
Hi,
Since @DataDavD's last message is three months old, I would like to give it a try if it's OK to everyone.

@agateau-gg is [this first commit](https://github.com/GitGuardian/ggshield/compare/main...RaoufCherif:ggshield:464/use_pathlib_instead_of_str) what you have in mind? let me know if I can contenue with the rest of the refactoring

**Comment by agateau-gg** [comment]
> Hi, Since @DataDavD's last message is three months old, I would like to give it a try if it's OK to everyone.

Hi, sincewe haven't heard from @DataDavD, you are welcome to give it a try 👍🏻.

> @agateau-gg is [this first commit](https://github.com/GitGuardian/ggshield/compare/main...RaoufCherif:ggshield:464/use_pathlib_instead_of_str) what you have in mind? let me know if I can contenue with the rest of the refactoring

Your commit is a good start, but it's changing the signature of `load_yaml_dict()` without taking advantage of the fact that the function now receives a Path instance. You can change it to  use `path.is_file()` instead of `os.path.isfile()`, and `path.open()` instead of `open(path)`.
