### ISSUE TITLE
Error messages displayed and shell must be interrupted after using ggshield auth login on Ubuntu using Microsoft Edge as default browser

### ISSUE THREAD

**Issue by nathaner** [GitGuardian/ggshield#466]
## Environment

- ggshield version: 1.14.2
- Operating system (Linux, macOS, Windows): Ubuntu
- Operating system version: 22.04.1 LTS
- Python version: 3.10.4

## Describe the bug

When signing in using `ggshield auth login` on Microsoft Edge on Ubuntu, when the authentication flow is finished, some error messages are displayed on the shell and they continue to be added as if the command hasn't exited. We need to abort the program using Ctrl-C to exit this.

Steps to reproduce:

1. Set your default browser to Microsoft Edge on an Ubuntu workstation
2. Make sure you don't have any Microsoft Edge window opened
3. Run command `ggshield auth login`
4. Finish the authentication flow

Actual result:

An error message is displayed in your shell. However, the authentication flow is successful.

![image](https://user-images.githubusercontent.com/25883088/215842609-a94c26ca-500b-4bbe-9da5-f8fe8f0ccfb6.png)

Expected result:

The behavior should be identical to the behavior with other browsers: no error message and we can interact with the shell when the authentication flow is finished.

**Comment by agateau-gg** [comment]
I am quite confident these messages are printed by Microsoft Edge itself, not by GGShield. You can verify this by starting Edge from the command line.

What happens here is that GGShield starts Edge, finishes its authentication process and exits, but Edge continues to run. As long as it runs it may continue printing log messages.

The browser is started using [webbrowser.open_new_tab](https://docs.python.org/3/library/webbrowser.html#webbrowser.open_new_tab) so we can't redirect its stdout and stderr to /dev/null. As such, I think we should close this as wontfix, if you don't mind.

**Comment by nathaner** [comment]
Ok, we can close as wontfix. Thanks for looking into this issue.
