### ISSUE TITLE
`ggshield secret scan docker` scans all versions of images if `:latest` is omitted

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#468]
## Environment

- ggshield version: 1.14.3
- Operating system (Linux, macOS, Windows): -
- Operating system version: -
- Python version: -

## Describe the bug

Steps to reproduce:

When scanning a Docker image using `ggshield secret scan docker` without adding the `:latest` tag, ggshield downloads **all** versions of the image.

1. Run command `ggshield secret scan docker gitguardian/ggshield:latest`
2. Notice it scanned 186 files and took 6s
3. Run command `ggshield secret scan docker gitguardian/ggshield`

Actual result:

GGShield scanned 188 files and took 35s.

Expected result:

GGShield should only have scanned 186 files in 6s.

The difference in number of files is not large here, but it could be on other images. The difference in execution time is massive.

## Explanation

Under the hood, GGShield runs `docker save <image_name> -o archive.tar`. Unlike other docker commands, `docker save` does not automatically append `:latest` if it's not present (see [`docker save` doc](https://docs.docker.com/engine/reference/commandline/save/))

## TODO

- [ ] Before running `docker save`, check if the image name includes a tag. If it's not the case, append `:latest` to it.

**Comment by karo-fox** [comment]
Can I take this one?

**Comment by agateau-gg** [comment]
Sure, go for it!

**Comment by karo-fox** [comment]
I have a question:

In case the image doesn't exist, we try to pull it. Then, when it is not found, we raise `UsageError` with `Image "{image_name}" not found`. Should image_name be just image_name, or have `:latest` appended to it?

**Comment by agateau-gg** [comment]
It sounds better to add `:latest`, because this way the user knows what we tried to pull. This is useful in case there is no `latest` tag for this image.
