### ISSUE TITLE
question: automated gitguardian does detect .gitguardian.yaml file.

### ISSUE THREAD

**Issue by armfazh** [GitGuardian/ggshield#490]
When gitguardian is installed in a github repo, where does the `.gitguardian.yaml` file should be located? (not a github action)
I see in the dashboard can be excluded some files, but apparently does not detect the local configuration file.

**Comment by pierrelalanne** [comment]
Hello @armfazh,
Thanks for your interest in ggshield.
Your configuration file for ggshield can be located either in your home directory, or at the root of your repository. See this [documentation](https://docs.gitguardian.com/ggshield-docs/configuration#configuration-files) for more details.
I hope this answers your question.

**Comment by armfazh** [comment]
Thanks for your response. I'm configuring a repo, but gitguardian does not detect the configuration file. However, I have no minimal example that shows there is an issue. I will report once it's verified.

**Comment by agateau-gg** [comment]
There may be some confusion here: the `.gitguardian.yaml` file is only read by GGShield, not by the web interface.

**Comment by armfazh** [comment]
if that's the case, then it should be possible that the web interface read the configuration file. 

In my setting, I have no access to the dashboard as my repo is in a corporate environment, but it should be possible to use some configuration per-repo basis.

**Comment by pierrelalanne** [comment]
Hi @armfazh,
Thanks for the details. All in all, my understanding is that you want to get rid of a couple of false positives that are triggered by GitGuardian in your dashboard ? You may want to have a look at the [filepath exclusion feature](https://docs.gitguardian.com/internal-repositories-monitoring/detect/customize-detection#exclude-filepaths) that we support at a global level in the dashboard.  
If this does not meet your need, feel free to submit an idea in our [prodcutboard roadmap](https://roadmap.gitguardian.com/tabs/10-ongoing).

**Comment by armfazh** [comment]
> All in all, my understanding is that you want to get rid of a couple of false positives that are triggered by GitGuardian in your dashboard ? 

This assessment partially correct, I want to be able to skip some files **without** using the dashboard, and using instead the configuration file in my repo.

I just submit the idea as suggested.
