### ISSUE TITLE
Command line options to recursively search other repositories for secrets

### ISSUE THREAD

**Issue by aaronatp** [GitGuardian/ggshield#689]
Hello, I thought it might be helpful when scanning a git repository to implement a couple of command line options to recursively search through other repositories for secrets: 

1) One command line option (say, "--recursive-contributors") might initially search through one repository looking for secrets, and then it would look at all of the other repositories which contributors have pushed code to, and look for secrets in that code. Even if a contributor has not revealed secrets in the initial repository, they may have revealed e.g. API keys in another repository that can be used to compromise the initial repository. A feature like this would probably be very helpful for businesses and pentesters.

2) Another command line option (say, "--recursive-owner") might initially search through one repository, and then see what other public repositories the repo owner has, and then search through all of them for secrets. This feature would likely be very helpful for many people as well and would help to automate a lot of secret-hunting.

Are these features ggshield would be interested in? If so, I would be very happy to write some code for them.

EDIT: By the way, loving the product! I only started using it last night and I've already found 3-4 secrets in a few large open source projects :)

**Comment by agateau-gg** [comment]
Hello!

Great to hear you like ggshield!

I think the feature would not be adapted to ggshield: the number of repositories to clone could easily balloon. But what you describe sounds a lot like our [Public Monitoring product](https://www.gitguardian.com/monitor-public-github-for-secrets). This product can, among other things:

> Map your attack surface on public GitHub
>
> - **Set up a dynamic perimeter including every developer related to your organization**
>
> - **Monitor all your developers’ public activity, even on personal GitHub repositories**
>
> - Track keywords specific to your organization  (e.g project names, IP addresses…)

I am going to close this issue as "not planned". Let me know if you need more info about Public Monitoring.

**Comment by aaronatp** [comment]
@agateau-gg No worries, thank you for letting me know about the Public Monitoring product. I wasn't aware of it but it sounds very interesting. I appreciate your consideration!
