### ISSUE TITLE
Your service is spam and scum 

### ISSUE THREAD

**Issue by DidacLL** [GitGuardian/ggshield#793]
If i never ask for your services why are you mailing me as if you where an authorised github service? And offering me non asked security?? That sounds me like the old avast tactics that were illegal here in Europe... Take care cause a big compliance about personal data leaking from github to your completely fraudulent activity may be a great headache also for big companies . Greetings.

**Comment by agateau-gg** [comment]
Hi Didac,

Our scanners detected secrets recently leaked using your account. We are sorry if the message we sent annoyed you.

Some of these secrets may still be valid and could be used to impersonate you. This is serious matter. Consider revoking them if you haven't done so already.
