### ISSUE TITLE
Sarif Output Format Support

### ISSUE THREAD

**Issue by Jiri-Stary** [GitGuardian/ggshield#869]
## Is your feature request related to a problem? Please describe.

I would like to get the output of ggshield in SARIF format, so it can be process afterwards.
My goal is to unify scanning experience with multiple scanning  tools, so i can show aggregated vulnerability information (number of issues and their severity)  on github workflow runs and / or on PRs.

## A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Current json output is undocumented and does note define a schema

## Describe the solution you'd like

Provide option to define additional output format as SARIF instead of json.

**Comment by mathieubellon** [comment]
Hi @Jiri-Stary 
FYI [GGShield 1.30](https://github.com/GitGuardian/ggshield/releases/tag/v1.30.1) is now supporting an XML output (SARIF format)
