### ISSUE TITLE
Gitguardian GitHub integration is not working

### ISSUE THREAD

**Issue by piyasith** [GitGuardian/ggshield#969]
## Environment

- GitHub

## Describe the bug

When I'm trying to integrate Gitguardian with our GitHub organization the Gitguardian GitHub app is installing to our organization, but the Gitguardian dashboard is showing "Not Installed". 

PS: I'm using the free tier of GitGuardian

Steps to reproduce:

1. In the integration page, click on the GitHub install
2. Grant access from the GitHub

GitHub App

<img width="646" alt="image" src="https://github.com/user-attachments/assets/ff178832-cd30-43fd-9545-ea34516aea9f">

In GitGuardian Dashboard

<img width="620" alt="Screenshot 2024-09-27 131542" src="https://github.com/user-attachments/assets/a253f26b-b62d-4bbc-8269-43a2a1413056">

<img width="716" alt="image" src="https://github.com/user-attachments/assets/92aca3d7-027c-4756-97ca-cd4811d89b6e">

**Comment by mathieubellon** [comment]
Hi @piyasith this looks like more an issue with the platform than our CLI (this repository) - could you please ask the support from the dashboard to help you out ?
