### ISSUE TITLE
`ggshield install --mode global` fails on Windows

### ISSUE THREAD

**Issue by mherzberg** [GitGuardian/ggshield#972]
## Environment

- ggshield version: 1.32.1
- Operating system (Linux, macOS, Windows): Windows 11
- Operating system version: 23H2
- Python version: 3.10.11 (I believe - whatever is part of your [self-contained Windows release](https://github.com/GitGuardian/ggshield/releases/download/v1.32.1/ggshield-1.32.1-x86_64-pc-windows-msvc.zip))

## Describe the bug

`ggshield install --mode global` fails to install the pre-commit hook.

I suspect this is because of changes introduced through [this PR](https://github.com/GitGuardian/ggshield/pull/970), which added [`env["GIT_CONFIG_GLOBAL"] = os.getenv("GG_GIT_CONFIG", "")`](https://github.com/GitGuardian/ggshield/blob/v1.32.1/ggshield/utils/git_shell.py#L196) among other git config related changes. The PR comment "Set the appropriate environment variables to ignore any git configuration." appears to assume the code is only used for read operations on the config file. However, as seen in the stack trace below, the code is also executed when setting `core.hooksPath`. 

Steps to reproduce:

1. Download the latest self-contained ggshield version for Windows.
2. Run `ggshield install --mode global` on a Windows machine.
3. The installation fails, as shown below.

Actual result:

Version 1.32.1 fails to install the pre-commit hook:

```
PS C:\Users\User\Downloads\ggshield-1.32.1-x86_64-pc-windows-msvc\ggshield-1.32.1-x86_64-pc-windows-msvc> .\ggshield.exe install --mode global
Traceback (most recent call last):
  File "ggshield\__main__.py", line 194, in <module>
  File "ggshield\__main__.py", line 190, in main
  File "click\[core.py](http://core.py/)", line 1078, in main
  File "click\[core.py](http://core.py/)", line 1688, in invoke
  File "click\[core.py](http://core.py/)", line 1434, in invoke
  File "click\[core.py](http://core.py/)", line 783, in invoke
  File "ggshield\cmd\[install.py](http://install.py/)", line 57, in install_cmd
  File "ggshield\cmd\[install.py](http://install.py/)", line 70, in install_global
  File "ggshield\utils\git_shell.py", line 230, in git
  File "ggshield\utils\git_shell.py", line 204, in git
  File "[subprocess.py](http://subprocess.py/)", line 526, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Git\\cmd\\git.EXE', 'config', '--global', 'core.hooksPath', 'C:\\Users\\User\\.git\\hooks']' returned non-zero exit status 4.
[17472] Failed to execute script '__main__' due to unhandled exception!
```

Expected result:

Version 1.32.0 installed fine, I expect version 1.32.1 to also install fine:

```
PS C:\Users\User\Downloads\ggshield-1.32.0-x86_64-pc-windows-msvc\ggshield-1.32.0-x86_64-pc-windows-msvc> .\ggshield.exe install --mode global
pre-commit successfully added in C:\Users\User\.git\hooks\pre-commit
A new version of ggshield (v1.32.1) has been released (https://github.com/GitGuardian/ggshield).
PS C:\Users\User\Downloads\ggshield-1.32.0-x86_64-pc-windows-msvc\ggshield-1.32.0-x86_64-pc-windows-msvc>
```

**Comment by Mohamed198-cup** [comment]
> ## وسط
> * إصدار GGSHIELD: 1.32.1
> * نظام التشغيل (لينكس، ماك، ويندوز): ويندوز 11
> * إصدار نظام التشغيل: 23H2
> * إصدار بايثون: 3.10.11 (على ما أعتقد - كل ما هو جزء من [إصدار Windows القائم بذاته](https://github.com/GitGuardian/ggshield/releases/download/v1.32.1/ggshield-1.32.1-x86_64-pc-windows-msvc.zip))
> 
> ## صف الخطأ
> `ggshield install --mode global` فشل في تثبيت خطاف الالتزام المسبق.
> 
> أظن أن هذا بسبب التغييرات التي تم إدخالها من خلال [هذا العلاقات العامة](https://github.com/GitGuardian/ggshield/pull/970) ، والتي تمت إضافتها [](https://github.com/GitGuardian/ggshield/blob/v1.32.1/ggshield/utils/git_shell.py#L196) من بين التغييرات الأخرى المتعلقة بتكوين git. يبدو أن تعليق العلاقات العامة "قم بتعيين متغيرات البيئة المناسبة لتجاهل أي تكوين git." يفترض أن الكود يستخدم فقط لعمليات القراءة في ملف التكوين. ومع ذلك ، كما هو موضح في تتبع المكدس أدناه ، يتم تنفيذ التعليمات البرمجية أيضا عند الإعداد.`core.hooksPath`
> 
> خطوات التكاثر:
> 
> 1. قم بتنزيل أحدث إصدار من ggshield قائم بذاته لنظام التشغيل Windows.
> 2. تشغيل على جهاز ويندوز.`ggshield install --mode global`
> 3. فشل التثبيت، كما هو موضح أدناه.
> 
> النتيجة الفعلية:
> 
> فشل الإصدار 1.32.1 في تثبيت خطاف الالتزام المسبق:
> 
> ```
> PS C:\Users\User\Downloads\ggshield-1.32.1-x86_64-pc-windows-msvc\ggshield-1.32.1-x86_64-pc-windows-msvc> .\ggshield.exe install --mode global
> Traceback (most recent call last):
>   File "ggshield\__main__.py", line 194, in <module>
>   File "ggshield\__main__.py", line 190, in main
>   File "click\[core.py](http://core.py/)", line 1078, in main
>   File "click\[core.py](http://core.py/)", line 1688, in invoke
>   File "click\[core.py](http://core.py/)", line 1434, in invoke
>   File "click\[core.py](http://core.py/)", line 783, in invoke
>   File "ggshield\cmd\[install.py](http://install.py/)", line 57, in install_cmd
>   File "ggshield\cmd\[install.py](http://install.py/)", line 70, in install_global
>   File "ggshield\utils\git_shell.py", line 230, in git
>   File "ggshield\utils\git_shell.py", line 204, in git
>   File "[subprocess.py](http://subprocess.py/)", line 526, in run
> subprocess.CalledProcessError: Command '['C:\\Program Files\\Git\\cmd\\git.EXE', 'config', '--global', 'core.hooksPath', 'C:\\Users\\User\\.git\\hooks']' returned non-zero exit status 4.
> [17472] Failed to execute script '__main__' due to unhandled exception!
> ```
> 
> النتيجة المتوقعة:
> 
> تم تثبيت الإصدار 1.32.0 بشكل جيد ، وأتوقع أن يتم تثبيت الإصدار 1.32.1 بشكل جيد أيضا:
> 
> ```
> PS C:\Users\User\Downloads\ggshield-1.32.0-x86_64-pc-windows-msvc\ggshield-1.32.0-x86_64-pc-windows-msvc> .\ggshield.exe install --mode global
> pre-commit successfully added in C:\Users\User\.git\hooks\pre-commit
> A new version of ggshield (v1.32.1) has been released (https://github.com/GitGuardian/ggshield).
> PS C:\Users\User\Downloads\ggshield-1.32.0-x86_64-pc-windows-msvc\ggshield-1.32.0-x86_64-pc-windows-msvc>
> ```

**Comment by agateau-gg** [comment]
Good catch, this is indeed a regression of 1.32.1. Looking into it.

**Comment by rgajason** [comment]
Could we get a release with this fix?  This has been pretty impacting for us.  Or is there a "last known good" version?
