### ISSUE TITLE
pre-commit warning

### ISSUE THREAD

**Issue by dotysan** [GitGuardian/ggshield#980]
[WARNING] repo `https://github.com/gitguardian/ggshield` uses deprecated stage names (commit, push) which will be removed in a future version.

**Comment by tapple-cisco** [comment]
as far as I can tell, this is just a doc bug. The full warning is
```
[WARNING] hook id `ggshield` uses deprecated stage names (commit) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
If I run the suggested command `pre-commit migrate-config`, it makes the following changes:
```
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -14,10 +14,10 @@ repos:
     hooks:
     -   id: ggshield
         language_version: python3
-        stages: [commit]
+        stages: [pre-commit]
 -   repo: https://github.com/gitguardian/ggshield
     rev: v1.32.0
     hooks:
     -   id: ggshield-push
         language_version: python3
-        stages: [push]
+        stages: [pre-push]
```
So, the stages just need to be modified in these 2 doc pages:
- https://docs.gitguardian.com/ggshield-docs/integrations/git-hooks/pre-commit
- https://docs.gitguardian.com/ggshield-docs/integrations/git-hooks/pre-push

**Comment by agateau-gg** [comment]
Hi, thanks for the suggestion, this change should appear in the public doc soon.

**Comment by agateau-gg** [comment]
The changes have been deployed.

**Comment by Crocmagnon** [comment]
I believe this should be reopened.
I just received the same warning on a repository *using* ggshield's pre-commit hook.

The full warning message is:
```
[WARNING] repo `https://github.com/gitguardian/ggshield` uses deprecated stage names (commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/gitguardian/ggshield` will fix this.  if it does not -- consider reporting an issue to that repo.
```

Running the suggested command doesn't fix the issue.

The stages should be modified in the [hooks file](https://github.com/GitGuardian/ggshield/blob/main/.pre-commit-hooks.yaml) so that a very minimal local config doesn't report a warning:

```yaml
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.34.0
    hooks:
      - id: ggshield
```
